# Generated by Django 4.0 on 2024-05-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_alter_serviceorders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorders',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='serviceorders',
            name='image_url',
            field=models.CharField(max_length=100, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='serviceorders',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
