# Generated by Django 4.0 on 2024-05-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_alter_serviceorders_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorders',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='service_orders/'),
        ),
    ]
