# Generated by Django 4.0 on 2024-05-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
        ('reservations', '0002_alter_carreservations_id_alter_spacereservations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservations',
            name='apartment',
            field=models.CharField(max_length=100, verbose_name='Apartamento'),
        ),
        migrations.AlterField(
            model_name='carreservations',
            name='tenant_name',
            field=models.CharField(max_length=100, verbose_name='Locatário'),
        ),
        migrations.AlterField(
            model_name='carreservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='spacereservations',
            name='apartment',
            field=models.CharField(max_length=100, verbose_name='Apartamento'),
        ),
        migrations.AlterField(
            model_name='spacereservations',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='spacereservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Usuário'),
        ),
    ]
