# Generated by Django 5.0.3 on 2024-04-02 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondominiumDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
