# Generated by Django 4.0 on 2024-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_userdocuments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumdocuments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
