# Generated by Django 4.0 on 2024-05-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
        ('documents', '0006_alter_condominiumdocuments_doc_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumdocuments',
            name='doc_name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='condominiumdocuments',
            name='doc_url',
            field=models.FileField(upload_to='cond_docs/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='doc_name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='doc_url',
            field=models.FileField(upload_to='user_docs/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Usuário'),
        ),
    ]
