# Generated by Django 4.0 on 2024-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocations', '0002_alter_convocations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocations',
            name='doc_url',
            field=models.FileField(upload_to='convocations/'),
        ),
    ]
