# Generated by Django 4.0 on 2024-05-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocations', '0003_alter_convocations_doc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocations',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='convocations',
            name='doc_url',
            field=models.FileField(upload_to='convocations/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='convocations',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
