# Generated by Django 5.0.3 on 2024-04-02 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('doc_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('doc_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugestionBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('doc_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulPhonesBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('doc_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
