# Generated by Django 4.0 on 2024-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_eventboard_id_alter_noticeboard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventboard',
            name='doc_url',
            field=models.FileField(upload_to='event_boards/'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='doc_url',
            field=models.FileField(upload_to='notice_boards/'),
        ),
        migrations.AlterField(
            model_name='sugestionboard',
            name='doc_url',
            field=models.FileField(upload_to='sugestion_boards/'),
        ),
        migrations.AlterField(
            model_name='usefulphonesboard',
            name='doc_url',
            field=models.FileField(upload_to='useful_phones_boards/'),
        ),
    ]
