# Generated by Django 4.0 on 2024-05-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_eventboard_doc_url_alter_noticeboard_doc_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventboard',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='eventboard',
            name='doc_url',
            field=models.FileField(upload_to='event_boards/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='eventboard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='doc_url',
            field=models.FileField(upload_to='notice_boards/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sugestionboard',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sugestionboard',
            name='doc_url',
            field=models.FileField(upload_to='sugestion_boards/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='sugestionboard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='usefulphonesboard',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='usefulphonesboard',
            name='doc_url',
            field=models.FileField(upload_to='useful_phones_boards/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usefulphonesboard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
